### ISSUE TITLE
Error: you shouldn't compose a transformed operation because composition and transformation are not compatible

### ISSUE THREAD

**Issue by homsterius** [Operational-Transformation/operational-transformation.github.com#33]
Hi, I stumble upon a bug, and this is what I did step by step to get it:

* Alice
	* Lorem ipsum
* Bob
	* Lorem ipsum

Alice removes last char "m"

* Alice
	* Lorem ipsu
* Bob
	* Lorem ipsum

Server receives new operation from Alice

Bob appends "x"

Server receives new operation from Bob

* Alice
	* Lorem ipsu
* Bob
	* Lorem ipsumx

Bob appends another "x"

* Alice
	* Lorem ipsu
* Bob
	* Lorem ipsumxx

Bob receives new operation (delete m)

* Alice
	* Lorem ipsu
* Bob
	* Lorem ipsuxx

Then Bob tries to append another x and error appears:
<img width="1678" alt="Screenshot 2021-05-07 at 21 49 41" src="https://user-images.githubusercontent.com/6019886/117495359-2bc4f400-af7e-11eb-8030-5dc0346f7717.png">

**Comment by timjb** [comment]
Fixed. @homsterius Thanks for the report!
