### ISSUE TITLE
Visualiser page no longer loads

### ISSUE THREAD

**Issue by ethangk** [Operational-Transformation/operational-transformation.github.com#7]
The error is "Uncaught ReferenceError: str is not defined", which is the line found <a href="https://github.com/Operational-Transformation/operational-transformation.github.com/blob/source/coffee/visualization.coffee#L71">here</a>. Perhaps that should be @str instead of str?

**Comment by timjb** [comment]
I guess that code compiled correctly with previous versions of Coffeescript, until the compilation of functions accepting arguments prefixed with `@` was changed.

**Comment by ethangk** [comment]
No problem, thanks for the library!
